services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - airflow_network  

  airflow:
    build: .
    container_name: airflow_container
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://myuser:mypassword@postgres:5432/mydatabase
      AIRFLOW__WEBSERVER__WEB_SERVER_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./my_dbt_project:/opt/airflow/my_dbt_project/my_dbt_project
      - ./profiles:/home/airflow/.dbt
    networks:
      - airflow_network
    command:
      - bash
      - -c
      - airflow db init && airflow webserver

volumes:
  postgres_data:
  airflow_data:

networks:
  airflow_network:
    driver: bridge
